const SET_OFFSET = "SET_OFFSET";
const SET_FILTER_DATA = "SET_FILTER_DATA";
const SET_PER_PAGE = "SET_PER_PAGE";
const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export { SET_OFFSET, SET_FILTER_DATA, SET_PER_PAGE, SET_SEARCH_TERM };
